### ISSUE TITLE
Consider retrieving privileged device/system information

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/ghw#108]
One of the design constraints of `ghw` is that we retrieve information that unprivileged users can retrieve and do not attempt to retrieve information from superuser-restricted areas (like `/sys/firmware/dmi/tables/DMI` on Linux for example).

There have been a number of requests, however, to have `ghw` dig for privileged information about baseboard information (Issue #96), certain firmware, hardware RAID controller information (Issue #94), and certain information that is only available to root/privileged users.

Consider relaxing the design constraint about unprivileged operations and attempt to retrieve information from privileged locations, but always fall back on a safe operation that doesn't return errors to the user, instead simply emitting warnings and setting requested information to some empty default values.

**Comment by chatenilesh** [comment]
If you are planning to get information from DMI following library could help:
https://github.com/digitalocean/go-smbios

I could help in implementation if you have a list of TODO(s) for getting information using DMI.

**Comment by jaypipes** [comment]
Hi @chatenilesh, yes, that exact library was brought up in Issue #96 :)

I'll try to go through the codebase and add some TODO annotations that you can use to find areas to work on.
