### ISSUE TITLE
Compilation error on Mac OS

### ISSUE THREAD

**Issue by jmozah** [jaypipes/ghw#118]
When i try to compile a simple program,

```
memory, _ := ghw.Memory()
fmt.Printf("%v\n", memory)
```
i get a compilation error like below

```
jaypipes/ghw/block_darwin.go:217:4: "cannot use infoPlist.BusProtocol (type string) as type BusType in field value"
```

I am using mac os Mojave

**Comment by jaypipes** [comment]
Hi! Please see #116 and #117. We're trying to figure out how to determine the disk and bus type on MacOS properly...
