### ISSUE TITLE
ghw Block doesnt list sd card

### ISSUE THREAD

**Issue by LukasMarckmiller** [jaypipes/ghw#132]
Im running ghw on an ARM Single Board Computer (ROCKPro64) with Armbian Linux. 
lsblk lists the device named "mmcblk0" as disk with a partition mounted to /.
But ghw doesn´t find anything. Filesystem is ext4 and its neither encrypted, nor are there some special rights set to dev. 

**lab02@rockpro64:/sys/block/mmcblk0$ lsblk**
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda           8:0    1  15.1G  0 disk 
└─sda1        8:1    1  15.1G  0 part /media/16GBStick
mtdblock0    31:0    0     4M  0 disk 
mtdblock1    31:1    0    32K  0 disk 
mtdblock2    31:2    0   256K  0 disk 
**_mmcblk0     179:0    0 238.5G  0 disk 
└─mmcblk0p1 179:1    0 236.1G  0 part /_**
zram0       252:0    0    50M  0 disk /var/log
zram1       252:1    0   256M  0 disk [SWAP]
zram2       252:2    0   256M  0 disk [SWAP]
zram3       252:3    0   256M  0 disk [SWAP]

**lab02@rockpro64:/sys/block/mmcblk0$ df -Th** 
Filesystem     Type      Size  Used Avail Use% Mounted on
udev           devtmpfs  1.9G     0  1.9G   0% /dev
tmpfs          tmpfs     388M  5.5M  383M   2% /run
**_/dev/mmcblk0p1 ext4      233G   18G  213G   8% /_**
tmpfs          tmpfs     1.9G   18M  1.9G   1% /dev/shm
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs     1.9G     0  1.9G   0% /sys/fs/cgroup
tmpfs          tmpfs     1.9G  6.4M  1.9G   1% /tmp
/dev/zram0     ext4       49M  4.5M   41M  10% /var/log
tmpfs          tmpfs     388M  5.3M  383M   2% /run/user/1000
overlaid       overlay   388M  5.3M  383M   2% /run/user/1000/lab02-chromium
/dev/sda1      vfat       16G  8.0K   16G   1% /media/16GBStick

**gwh only lists sda1**

**Comment by LukasMarckmiller** [comment]
**lab02@rockpro64:/sys$ fdisk -l**

Disk /dev/mtdblock0: 4 MiB, 4161536 bytes, 8128 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
Disk /dev/mtdblock1: 32 KiB, 32768 bytes, 64 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
 
Disk /dev/mtdblock2: 256 KiB, 262144 bytes, 512 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
 
**Disk /dev/mmcblk0: 238.5 GiB, 256087425024 bytes, 500170752 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x718c04a5**
 
Device         Boot Start       End   Sectors   Size Id Type
/dev/mmcblk0p1      32768 495169023 495136256 236.1G 83 Linux
 
 
Disk /dev/sda: 15.1 GiB, 16261316608 bytes, 31760384 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2f199797
 
Device     Boot Start      End  Sectors  Size Id Type
/dev/sda1  *     2048 31760383 31758336 15.1G  c W95 FAT32 (LBA)
lab02@rockpro64:/sys$ sudo fdisk -l
[sudo] password for lab02:
Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/mtdblock0: 4 MiB, 4161536 bytes, 8128 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
 
Disk /dev/mtdblock1: 32 KiB, 32768 bytes, 64 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
 
Disk /dev/mtdblock2: 256 KiB, 262144 bytes, 512 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
 
 
Disk /dev/mmcblk0: 238.5 GiB, 256087425024 bytes, 500170752 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x718c04a5
 
Device         Boot Start       End   Sectors   Size Id Type
/dev/mmcblk0p1      32768 495169023 495136256 236.1G 83 Linux
 
 
Disk /dev/zram0: 50 MiB, 52428800 bytes, 12800 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/zram1: 256 MiB, 268435456 bytes, 65536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/zram2: 256 MiB, 268435456 bytes, 65536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/zram3: 256 MiB, 268435456 bytes, 65536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/zram4: 256 MiB, 268435456 bytes, 65536 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
 
 
Disk /dev/sda: 15.1 GiB, 16261316608 bytes, 31760384 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2f199797
 
Device     Boot Start      End  Sectors  Size Id Type
/dev/sda1  *     2048 31760383 31758336 15.1G  c W95 FAT32 (LBA)

**Comment by jaypipes** [comment]
Thanks for the bug report @LukasMarckmiller! I'll look into this issue ASAP.

**Comment by LukasMarckmiller** [comment]
I used this sd card btw 
https://www.amazon.de/Samsung-Micro-256GB-Speicherkarte-Adapter/dp/B06XFS5657

**Comment by jaypipes** [comment]
@LukasMarckmiller hi again! If you would be able to test out PR #136 and see if this works properly for you now, that would be very useful, thanks!

**Comment by LukasMarckmiller** [comment]
Hey,

thank you for the fix. The card is visible now. The only problem is the size_bytes for the partition is 0. 
ghw lists following:
"mount_point": "/",
"name": "mmcblk0p1," 
"size_bytes":0
while lsblk lists:
**mmcblk0p1:     part     /     236,1G**
