### ISSUE TITLE
unknown disk bus path on Alpine

### ISSUE THREAD

**Issue by chrisvdg** [jaypipes/ghw#133]
For writing a CSI driver I'm using this library to list the disks on a node in a kubernetes cluster to be able to mount it, for finding the disks I'm using the disk bus path.

On the node itself running Ubuntu 16.04 and there I can see the bus paths of the disks clearly 

Code
```go
import (
	"fmt"
	"log"

	"github.com/jaypipes/ghw"
)

func main() {
	blockInfo, err := ghw.Block()
	if err != nil {
		log.Fatal(err)
	}

	for _, d := range blockInfo.Disks {
		fmt.Println(d.Name)
		fmt.Println(d.BusPath)
	}
}
```

output directly on node
```sh
vda
virtio-pci-0000:00:04.0
vdb
virtio-pci-0000:00:06.0
vdc
virtio-pci-0000:00:08.0
```

Executing the same code on the Alpine (3.8.4) deamonset container
```sh
vda
unknown
vdb
unknown
vdc
unknown
```

Listing disks by path inside the container
```sh
/ # ls -la /dev/disk/by-path/
total 0
drwxr-xr-x    2 root     root           160 Jun 19 14:45 .
drwxr-xr-x    6 root     root           120 Jun 18 00:46 ..
lrwxrwxrwx    1 root     root             9 Jun 18 00:46 virtio-pci-0000:00:04.0 -> ../../vda
lrwxrwxrwx    1 root     root            10 Jun 18 00:46 virtio-pci-0000:00:04.0-part1 -> ../../vda1
lrwxrwxrwx    1 root     root            11 Jun 18 00:46 virtio-pci-0000:00:04.0-part14 -> ../../vda14
lrwxrwxrwx    1 root     root            11 Jun 18 00:46 virtio-pci-0000:00:04.0-part15 -> ../../vda15
lrwxrwxrwx    1 root     root             9 Jun 18 00:46 virtio-pci-0000:00:06.0 -> ../../vdb
lrwxrwxrwx    1 root     root             9 Jun 19 14:45 virtio-pci-0000:00:09.0 -> ../../vdc
```

Expected the same output in the Alpine container as the Ubuntu host

**Comment by jaypipes** [comment]
@chrisvdg Thanks for the bug report. I'll take a look into this ASAP.

**Comment by jaypipes** [comment]
@chrisvdg could you please share the container setup/config you are using? I'm having a hard time reproducing this one.

**Comment by jaypipes** [comment]
Never mind @chrisvdg. I was able to reproduce it:

```
~/go/src/github.com/jaypipes/ghw # go run cmd/ghwc/main.go block
block storage (2 disks, 2TB physical storage)
 /dev/nvme0n1 SSD (233GB) NVMe [@unknown (node #0)] vendor=unknown
  /dev/nvme0n1p1 (499MB) 
  /dev/nvme0n1p2 (100MB) 
  /dev/nvme0n1p3 (16MB) 
  /dev/nvme0n1p4 (233GB) 
 /dev/sda SSD (932GB) SCSI [@unknown (node #0)] vendor=ATA
  /dev/sda1 (512MB) 
  /dev/sda2 (932GB) [ext4] mounted@/etc/resolv.conf
~/go/src/github.com/jaypipes/ghw # ls -la /dev/disk/by-path/
total 0
drwxr-xr-x    2 root     root           200 Jun 30 16:34 .
drwxr-xr-x    8 root     root           160 Jun 30 16:34 ..
lrwxrwxrwx    1 root     root            13 Jun 30 16:34 pci-0000:01:00.0-nvme-1 -> ../../nvme0n1
lrwxrwxrwx    1 root     root            15 Jun 30 16:34 pci-0000:01:00.0-nvme-1-part1 -> ../../nvme0n1p1
lrwxrwxrwx    1 root     root            15 Jun 30 16:34 pci-0000:01:00.0-nvme-1-part2 -> ../../nvme0n1p2
lrwxrwxrwx    1 root     root            15 Jun 30 16:34 pci-0000:01:00.0-nvme-1-part3 -> ../../nvme0n1p3
lrwxrwxrwx    1 root     root            15 Jun 30 16:34 pci-0000:01:00.0-nvme-1-part4 -> ../../nvme0n1p4
lrwxrwxrwx    1 root     root             9 Jun 30 16:34 pci-0000:02:00.1-ata-1 -> ../../sda
lrwxrwxrwx    1 root     root            10 Jun 30 16:34 pci-0000:02:00.1-ata-1-part1 -> ../../sda1
lrwxrwxrwx    1 root     root            10 Jun 30 16:34 pci-0000:02:00.1-ata-1-part2 -> ../../sda2
~/go/src/github.com/jaypipes/ghw # 
```

Will try to debug and fix today.

**Comment by jaypipes** [comment]
OK, figured it out. `ghw` uses udevadm to get the disk bus path. Alpine doesn't use udevadm (or udev apparently). I will go ahead and add fallbacks to use sysfs if udevadm isn't available.

**Comment by jaypipes** [comment]
Actually, I was wrong. We don't use udevadm. We look up the udev runtime DB via `/run/udev/data`, so in order to get ghw to work properly on Alpine, simply bind-mount `/run` to the container's `/run`:

```
jaypipes@thelio:~/src/github.com/jaypipes/ghw$ docker run --rm -it -v /dev/disk:/dev/disk -v /run:/run alpine:3.8.4 /bin/sh
/ # apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/29) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(2/29) Installing ncurses-terminfo (6.1_p20180818-r1)
(3/29) Installing ncurses-libs (6.1_p20180818-r1)
(4/29) Installing readline (7.0.003-r0)
(5/29) Installing bash (4.4.19-r1)
Executing bash-4.4.19-r1.post-install
(6/29) Installing binutils (2.30-r5)
(7/29) Installing gmp (6.1.2-r1)
(8/29) Installing isl (0.18-r0)
(9/29) Installing libgomp (6.4.0-r9)
(10/29) Installing libatomic (6.4.0-r9)
(11/29) Installing pkgconf (1.5.3-r0)
(12/29) Installing libgcc (6.4.0-r9)
(13/29) Installing mpfr3 (3.1.5-r1)
(14/29) Installing mpc1 (1.0.3-r1)
(15/29) Installing libstdc++ (6.4.0-r9)
(16/29) Installing gcc (6.4.0-r9)
(17/29) Installing musl-dev (1.1.19-r10)
(18/29) Installing libcrypto1.0 (1.0.2r-r0)
(19/29) Installing libssl1.0 (1.0.2r-r0)
(20/29) Installing openssl (1.0.2r-r0)
(21/29) Installing go (1.10.8-r0)
(22/29) Installing ca-certificates (20190108-r0)
(23/29) Installing nghttp2-libs (1.32.0-r0)
(24/29) Installing libssh2 (1.8.2-r0)
(25/29) Installing libcurl (7.61.1-r2)
(26/29) Installing expat (2.2.7-r0)
(27/29) Installing pcre2 (10.31-r0)
(28/29) Installing git (2.18.1-r0)
(29/29) Installing .build-deps (0)
Executing busybox-1.28.4-r3.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 431 MiB in 42 packages
/ # go get -u github.com/golang/dep/cmd/dep
/ # go get github.com/jaypipes/ghw
/ # export GOPATH=/root/go
/ # export PATH=$PATH:$GOPATH/bin
/ # cd root/go/src/github.com/jaypipes/ghw/
~/go/src/github.com/jaypipes/ghw # dep ensure -v
(1/9) Wrote github.com/pkg/errors@v0.8.0
(2/9) Wrote howett.net/plist (from github.com/DHowett/go-plist)@591f970eefbbeb04d7b37f334a0c4c3256e32876
(3/9) Wrote github.com/mitchellh/go-homedir@v1.0.0
(4/9) Wrote gopkg.in/yaml.v2@v2.2.2
(5/9) Wrote github.com/spf13/pflag@v1.0.2
(6/9) Wrote github.com/jaypipes/pcidb@0.4
(7/9) Wrote github.com/inconshreveable/mousetrap@v1.0
(8/9) Wrote github.com/spf13/cobra@v0.0.3
(9/9) Wrote github.com/ghodss/yaml@v1.0.0
~/go/src/github.com/jaypipes/ghw # go run cmd/ghwc/main.go block
block storage (2 disks, 2TB physical storage)
 /dev/nvme0n1 SSD (233GB) NVMe [@pci-0000:01:00.0-nvme-1 (node #0)] vendor=unknown model=Samsung SSD 970 EVO 250GB serial=S46CNX0KB01080P WWN=eui.0025385b81b22158
  /dev/nvme0n1p1 (499MB) 
  /dev/nvme0n1p2 (100MB) 
  /dev/nvme0n1p3 (16MB) 
  /dev/nvme0n1p4 (233GB) 
 /dev/sda SSD (932GB) SCSI [@pci-0000:02:00.1-ata-1 (node #0)] vendor=ATA model=Samsung_SSD_860_EVO_1TB serial=S3Z6NB0KC05827V WWN=0x5002538e40ace889
  /dev/sda1 (512MB) 
  /dev/sda2 (932GB) [ext4] mounted@/etc/resolv.conf
```

I'm going to close this issue out and add a note to the README about making sure you bindmount `/run` if you're running in a container.

**Comment by mudler** [comment]
Sorry for resurrecting an old thread, but I'm hitting this on a real live alpine system, where udev is running:

```
c3os:~$ ps aux | grep udev
root      1407  0.0  0.1   7068  2520 ?        Ss   21:46   0:00 /sbin/udevd
c3os      8435  0.0  0.0   1584   864 pts/0    S+   22:54   0:00 grep udev
```

I'm trying to read the data from `/udev`, but indeed something looks off as there is no data:

```
c3os:~$ sudo cat /sys/block/sda/sda1/dev
8:1
$ ls -liah /run/udev/data/
c10:200  c7:130   c7:131   c7:132   c7:133   c7:134   c7:2     c7:3     c7:4     c7:5     c7:6     c7:66    c7:67    c7:68    c7:69    c7:70    n3       
c3os:~$ ls -liah /run/udev/data/
total 0
15127 drwxr-xr-x 2 root root 380 May 10 21:46 .
13052 drwxr-xr-x 6 root root 140 May 10 21:46 ..
23453 -rw-r--r-- 1 root root   0 May 10 21:46 c10:200
23129 -rw-r--r-- 1 root root   0 May 10 21:46 c7:130
23136 -rw-r--r-- 1 root root   0 May 10 21:46 c7:131
23153 -rw-r--r-- 1 root root   0 May 10 21:46 c7:132
23165 -rw-r--r-- 1 root root   0 May 10 21:46 c7:133
23178 -rw-r--r-- 1 root root   0 May 10 21:46 c7:134
23121 -rw-r--r-- 1 root root   0 May 10 21:46 c7:2
23138 -rw-r--r-- 1 root root   0 May 10 21:46 c7:3
23145 -rw-r--r-- 1 root root   0 May 10 21:46 c7:4
23158 -rw-r--r-- 1 root root   0 May 10 21:46 c7:5
23171 -rw-r--r-- 1 root root   0 May 10 21:46 c7:6
23125 -rw-r--r-- 1 root root   0 May 10 21:46 c7:66
23140 -rw-r--r-- 1 root root   0 May 10 21:46 c7:67
23149 -rw-r--r-- 1 root root   0 May 10 21:46 c7:68
23162 -rw-r--r-- 1 root root   0 May 10 21:46 c7:69
23175 -rw-r--r-- 1 root root   0 May 10 21:46 c7:70
23458 -rw-r--r-- 1 root root   0 May 10 21:46 n3
```

ghw seems indeed to be able to detect the partition numbers, but not any details from it

**Comment by jaypipes** [comment]
> Sorry for resurrecting an old thread, but I'm hitting this on a real live alpine system, where udev is running:
> 
> ```
> c3os:~$ ps aux | grep udev
> root      1407  0.0  0.1   7068  2520 ?        Ss   21:46   0:00 /sbin/udevd
> c3os      8435  0.0  0.0   1584   864 pts/0    S+   22:54   0:00 grep udev
> ```
> 
> I'm trying to read the data from `/udev`, but indeed something looks off as there is no data:
> 
> ```
> c3os:~$ sudo cat /sys/block/sda/sda1/dev
> 8:1
> $ ls -liah /run/udev/data/
> c10:200  c7:130   c7:131   c7:132   c7:133   c7:134   c7:2     c7:3     c7:4     c7:5     c7:6     c7:66    c7:67    c7:68    c7:69    c7:70    n3       
> c3os:~$ ls -liah /run/udev/data/
> total 0
> 15127 drwxr-xr-x 2 root root 380 May 10 21:46 .
> 13052 drwxr-xr-x 6 root root 140 May 10 21:46 ..
> 23453 -rw-r--r-- 1 root root   0 May 10 21:46 c10:200
> 23129 -rw-r--r-- 1 root root   0 May 10 21:46 c7:130
> 23136 -rw-r--r-- 1 root root   0 May 10 21:46 c7:131
> 23153 -rw-r--r-- 1 root root   0 May 10 21:46 c7:132
> 23165 -rw-r--r-- 1 root root   0 May 10 21:46 c7:133
> 23178 -rw-r--r-- 1 root root   0 May 10 21:46 c7:134
> 23121 -rw-r--r-- 1 root root   0 May 10 21:46 c7:2
> 23138 -rw-r--r-- 1 root root   0 May 10 21:46 c7:3
> 23145 -rw-r--r-- 1 root root   0 May 10 21:46 c7:4
> 23158 -rw-r--r-- 1 root root   0 May 10 21:46 c7:5
> 23171 -rw-r--r-- 1 root root   0 May 10 21:46 c7:6
> 23125 -rw-r--r-- 1 root root   0 May 10 21:46 c7:66
> 23140 -rw-r--r-- 1 root root   0 May 10 21:46 c7:67
> 23149 -rw-r--r-- 1 root root   0 May 10 21:46 c7:68
> 23162 -rw-r--r-- 1 root root   0 May 10 21:46 c7:69
> 23175 -rw-r--r-- 1 root root   0 May 10 21:46 c7:70
> 23458 -rw-r--r-- 1 root root   0 May 10 21:46 n3
> ```
> 
> ghw seems indeed to be able to detect the partition numbers, but not any details from it. Note udevadm settle is called, and along all commands to populate devices

Hi @mudler! Would you mind opening a new issue for this please? Also, please let us know what version of `ghw` you are using. We actually just recently merged a couple commits that fix up Partition labeling on the main branch but not yet in a point release. I'm wondering if you might be able to pull the latest SHA for ghw and see if the latest still has the issue for you?

Best,
-jay

**Comment by mudler** [comment]
Hi @jaypipes ! thanks for the quick response!

After some debugging it turned out that it was a configuration issue. On alpine it seems that the `udev-trigger` service needs to be enabled as well in order to populate properly the udev db.

Thanks again!
