### ISSUE TITLE
Does this package support centos?

### ISSUE THREAD

**Issue by asdfsx** [jaypipes/ghw#148]
I'm trying to use `ghw` to gather memory informations on centos. But got the error `can not find /var/log/syslog`. 
Does the package support centos??

**Comment by jaypipes** [comment]
Hi @asdfsx, you are seeing a *warning* about not being able to read `/var/log/syslog`? It's not an error, but a warning. If you execute your program with root privileges, that warning will disappear. Alternately, set the `GHW_DISABLE_WARNINGS=1` environment variable to hide that warning message.

You can read more about that here: https://github.com/jaypipes/ghw#disabling-warning-messages
