### ISSUE TITLE
pkg\mod\github.com\jaypipes\ghw@v0.5.0\dmi_stub.go:15:39: undefined: DMIInfo  at windows

### ISSUE THREAD

**Issue by runner-mei** [jaypipes/ghw#161]
pkg\mod\github.com\jaypipes\ghw@v0.5.0\dmi_stub.go:15:39: undefined: DMIInfo  at windows

**Comment by jaypipes** [comment]
Hi @runner-mei! Thank you for the bug report! May I confirm that you are seeing this on Windows? If so, can you provide us some details about the version of Windows you are experiencing this on, please?

Thanks!
-jay

**Comment by runner-mei** [comment]
yes, it is windows10 home.  version is 1903

**Comment by jaypipes** [comment]
Hello again, @runner-mei. This was fixed with https://github.com/jaypipes/ghw/pull/147. I will be cutting a release of ghw within the next week that includes that patch. If you need an updated binary ASAP, you can pull in the specific `ghw` commit with the fix in your go.mod, like this:

```
go get github.com/jaypipes/ghw@2451355a
```

**Comment by jaypipes** [comment]
Please note, however, that while that will allow you to build on Windows, support for Windows hardware resources are coming in v1.0.0 of `ghw`, which is due out at the end of this month. Thanks!
