### ISSUE TITLE
Avoid warning message

### ISSUE THREAD

**Issue by tredoe** [jaypipes/ghw#174]
At Linux, when it is run the next code:

```
net, err := ghw.Network()
	if err != nil {
		t.Errorf("Error getting network info: %v", err)
	}
```
It is printed the next warning
> WARNING: ethtool not installed. Cannot grab NIC capabilities

but I want not that it been printed since to get the MAC address or the NIC name, I don't need that tool.

As suggestion, a boolean like 'printWarning' or 'skipWarning' could be added to `Network()`

**Comment by jaypipes** [comment]
Thanks for the bug report @tredoe! I'll look into this ASAP.

**Comment by jaypipes** [comment]
@tredoe simply set the `GHW_DISABLE_WARNINGS` environment variable to "1":

Please see this in the documentation:

https://github.com/jaypipes/ghw#disabling-warning-messages
