### ISSUE TITLE
Provide `ghw.WithDisableWarnings()` function

### ISSUE THREAD

**Issue by tredoe** [jaypipes/ghw#175]
https://github.com/jaypipes/ghw#disabling-warning-messages

Now, there is to use an environment variable to disable the warnings, but it is not an option when the package is going to be compiled into a main program.

The best would be to add a global variable at 'ghw' to disable them.

**Comment by jaypipes** [comment]
Are you referring to the `ghwc` CLI tool? Or are you referring to `import`ing the ghw library? In either case, the way to disable warning messages is to set the environment variable that the library looks for, which is `GHW_DISABLE_WARNINGS`.

If you are `import`ing the ghw library into your own executable and wish to always disable these warnings, then *your* code should simply call:

```go
import os

os.Setenv("GHW_DISABLE_WARNINGS", "1")
```

https://golang.org/pkg/os/#Setenv

before calling any `ghw` library functions.

Make sense?

**Comment by tredoe** [comment]
It does not make sense that a library use environment variables to enable/disable features on it.

**Comment by jaypipes** [comment]
@tredoe I could add a `ghw.WithDisableWarnings()` technique:

```go
net, err := ghw.Network(ghw.WithDisableWarnings())
```

similar to the `ghw.WithChroot()` function:

https://github.com/jaypipes/ghw#overriding-the-root-mountpoint-ghw-uses

https://github.com/jaypipes/ghw/blob/14923eaaa4d8378051f741694e261747d16fc05e/options.go#L34

that can be used to change the root directory path in addition to the `GHW_CHROOT` environment variable.

Would that be more amenable to you?

**Comment by tredoe** [comment]
Oh yes, please

**Comment by jaypipes** [comment]
> It does not make sense that a library use environment variables to enable/disable features on it.

Plenty of libraries control features using environment variables, by the way.

Examples:

* **Logrus**: https://github.com/sirupsen/logrus/blob/53000c4c0f981521df1bada12a9e9ea20728fb62/text_formatter.go#L116
* **Ginkgo**: https://github.com/onsi/ginkgo/blob/6a07ea2adeafc7c9dc2a9b38ffc4154f9159f467/ginkgo/run_command.go#L130
* **aws-sdk-go**: https://github.com/aws/aws-sdk-go/blob/bef02444773a49eaf30cdd615920b56896827c06/aws/credentials/env_provider.go#L44
* **cobra**: https://github.com/spf13/cobra/blob/1e58aa3361fd650121dceeedc399e7189c05674a/cobra/cmd/helpers.go#L31

lots more...

**Comment by tredoe** [comment]
> > It does not make sense that a library use environment variables to enable/disable features on it.
> 
> Plenty of libraries control features using environment variables, by the way.

So it is an error, since my point of view:

- When I use a library I want to be able to control all features of it, nor the final user.
- When I want that the final user can change some behaviour on the final executable, then I allow it at such executable.

**Comment by jaypipes** [comment]
I will implement a `ghw.WithDisableWarnings()` function, then.

**Comment by tredoe** [comment]
At Linux, the function `ghw.Baseboard()` also prints a warning:

```
WARNING: Unable to read board_serial: open /sys/class/dmi/id/board_serial: permission denied
```

**Comment by fromanirh** [comment]
I can take a stab at this issue: if we want uniformity from the behaviour we control using the env vars and programmatically; meaning: both interfaces should be equally poewerful, then I need to do a small change in the snapshot pkg anyway.

**Comment by fromanirh** [comment]
Fixed by https://github.com/jaypipes/ghw/pull/216 - we indeed added `ghw.WithDisableWarnings()` implemented on top of extra machinery to allow users to redirect where ghw sends warnings using a bare-bones interface, similar to the `log` package in spirit.
