### ISSUE TITLE
Block device serial number detection

### ISSUE THREAD

**Issue by antylama** [jaypipes/ghw#19]
Function DiskSerialNumber return only vendor name when parse disks like this:

`/dev/disk/by-id/ata-AXIOMTEK_Corp.-FSA032G300MW5T-H_BCA11704240020001`

or

`/dev/disk/by-id/ata-WDC_WD10JFCX-68N6GN0_WD-WX31A76R3KFS`

split by '-', return only secound part ('AXIOMTEK_Corp.' or 'WDC_WD10JFCX').

**Comment by jaypipes** [comment]
Hi!

In the above ATA disk examples, what is the serial number of the disk? Is it the last '-' separated component? Or is it everything after the vendor name?

In other words, for the above path:

`/dev/disk/by-id/ata-AXIOMTEK_Corp.-FSA032G300MW5T-H_BCA11704240020001`

is the serial number `FSA032G300MW5T-H_BCA11704240020001` or is the serial number `H_BCA11704240020001`?

Similarly, for the second path:

`/dev/disk/by-id/ata-WDC_WD10JFCX-68N6GN0_WD-WX31A76R3KFS`

is the serial number `WD10JFCX-68N6GN0_WD-WX31A76R3KFS`, `68N6GN0_WD-WX31A76R3KFS` or just `WX31A76R3KFS`?

Thanks!
-jay

**Comment by antylama** [comment]
Hi!

Axiomtek, checked few more tools:

user@ubuntu:~$ sudo hdparm -I /dev/sda | grep -E "Number"
Model Number:       AXIOMTEK Corp.-FSA032G300MW5T-H
Serial Number:      BCA11704240020001

user@ubuntu:~$ sudo lsblk --nodeps -o name,serial
/dev/disk/by-id/ata-AXIOMTEK_Corp.-FSA032G300MW5T-H_BCA11704240020001
NAME SERIAL
sda  BCA11704240020001

user@ubuntu:~$ inxi -Dxx
Drives:    HDD Total Size: 32.0GB (23.1% used)
           ID-1: /dev/sda model: AXIOMTEK_Corp. size: 32.0GB serial:
BCA11704240020001 temp: 52C

It's looks like in smartctl for "serial number" ("Model Number" in hdparm
==  "Device model" in smartctl).

best regards
Marcin

**Comment by antylama** [comment]
Text on AXIOMTEK sticker:

```
mSATA SATA3 MLC WT
P/N: FSA032G300MW5T-H 32GB
<BAR CODE>
BCA11704240020001
```
