### ISSUE TITLE
NUMA memory info

### ISSUE THREAD

**Issue by chabbimilind** [jaypipes/ghw#200]
The `Node` structure does not include per NUMA node physical memory statistics.

```
type Node struct {
	ID     int                  `json:"id"`
	Cores  []*cpu.ProcessorCore `json:"cores"`
	Caches []*memory.Cache      `json:"caches"`
}
``` 

Can we add `Memory []*memory.Info` field to the struct and provide per-NUMA-node memory stats?

On Linux, `/sys/devices/system/node/node*/meminfo ` file will offer the necessary data.
We need to augment `pkg/memory/memory_linux.go` with a function such as `MemoryForNode()` and call it from `func topologyNodes` in `pkg/topology/topology_linux.go`.

**Comment by fromanirh** [comment]
I'd happy to work in this area in the coming days/weeks.
