### ISSUE TITLE
[Question] How To Get GPU Info Like Neofetch

### ISSUE THREAD

**Issue by usdogu** [jaypipes/ghw#214]
this is the what neofetch shows info like : https://imgur.com/a/12SSXVk

**Comment by jaypipes** [comment]
```
[jaypipes@thelio ghw]$ go run cmd/ghwc/main.go gpu
gpu (1 graphics card)
 card #0 @0000:0a:00.0 -> class: 'Display controller' vendor: 'NVIDIA Corporation' product: 'TU106 [GeForce RTX 2070 Rev. A]'
```

What specifically are you looking for @usdogu?

**Comment by usdogu** [comment]
I am looking for GPU's brand and model combined 
for example according to your output I want a output like "NVIDIA TU106 [GeForce RTX 2070 Rev. A]"  (sorry for my bad english :p)

**Comment by jaypipes** [comment]
> sorry for my bad english :p)

No worries at all! :)

> I am looking for GPU's brand and model combined
> for example according to your output I want a output like "NVIDIA TU106 [GeForce RTX 2070 Rev. A]"

OK, you could do something like this:

```go
package main

import (
	"fmt"

	"github.com/jaypipes/ghw"
)

func main() {
	gpu, err := ghw.GPU()
	if err != nil {
		fmt.Printf("Error getting GPU info: %v", err)
	}

	for _, card := range gpu.GraphicsCards {
		if card.DeviceInfo != nil {
			fmt.Printf(" %s %s\n", card.DeviceInfo.Vendor.Name, card.DeviceInfo.Product.Name)
		}
	}
}
```

**Comment by usdogu** [comment]
sorry for late reply , thanks a lot
