### ISSUE TITLE
PCI: Migrate from BSF to BDF convention

### ISSUE THREAD

**Issue by pearsonk** [jaypipes/ghw#220]
Slot designation is a bit of a misnomer when referring to the addressing field, which is conventionally called Device in Domain:Bus:Device.Function notations.
Further, as it seems relevant, actual slot information can be pulled from DMI (type 9) with a lookup of the Designation for a matching Bus Address for the first Function of the device. Absence of a DMI entry would signify an internal PCI device not connected to an expansion slot.

**Comment by fromanirh** [comment]
fixed by https://github.com/jaypipes/ghw/pull/252
