### ISSUE TITLE
GHW crashes when /numa_node file does not exist

### ISSUE THREAD

**Issue by JustinTimperio** [jaypipes/ghw#234]
When running ghw on an AMD Ryzen 7 5800X running proxmox the following error causes not only ghw to crash but the whole application to panic. I suspect this may be an issue with the VM but it would be worth error handling events like this to minimize risk. The following error causes the full panic 
```WARNING: failed to read int from file: open /sys/class/drm/card0/device/numa_node: no such file or directory```

### System Info
```
       _,met$$$$$gg.          root@xxxxxxxx
    ,g$$$$$$$$$$$$$$$P.       --------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 10 (buster) x86_64
 ,$$P'              `$$$.     Host: X570 AORUS PRO -CF
',$$P       ,ggs.     `$$b:   Kernel: 5.4.78-2-pve
`d$$'     ,$P"'   .    $$$    Uptime: 12 hours, 54 mins
 $$P      d$'     ,    $$P    Packages: 782 (dpkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.0.3
 $$;      Y$b._   _,d$P'      Terminal: /dev/pts/11
 Y$$.    `.`"Y$$$$P"'         CPU: AMD Ryzen 7 5800X 8- (16) @ 3.800GHz
 `$$b      "-.__              GPU: NVIDIA GeForce GTX 1060 6GB
  `Y$$                        GPU: NVIDIA GeForce GT 610
   `Y$$.                      Memory: 10036MiB / 32054MiB
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
              ```

**Comment by jaypipes** [comment]
Hi @JustinTimperio! Are you running the `ghwc` client or are you importing ghw into your own source code? Also, please let us know what version of ghw you are using. Thanks!

**Comment by JustinTimperio** [comment]
Hi @jaypipes, This was being imported into our own source code (it catches errors if they occur) using version `0.7.0`. 
I suspect this was just an issue with a broken VM but it might be worth handling edge cases like that especially if they cause a full panic.

**Comment by jaypipes** [comment]
> Hi @jaypipes, This was being imported into our own source code (it catches errors if they occur) using version `0.7.0`.
> I suspect this was just an issue with a broken VM but it might be worth handling edge cases like that especially if they cause a full panic.

Cool, thanks for the heads up. Definitely ghw should not panic, so I'll look into things and make sure we're catching all exceptions appropriately.

**Comment by fromanirh** [comment]
Hey, I think I have some time to work on this issue.

**Comment by fromanirh** [comment]
Working on reproducer + enablement here: https://github.com/jaypipes/ghw/pull/235
I'll re-upload with a ghw snapshot ASAP, so we can reason about it.
@JustinTimperio looking at the code and while working on the reprouced is not yet obvious to me what exactly causes the issue.  could you please elaborate about the crash you had? I totally see the warning, but this should not directly lead to a crash.

**Comment by JustinTimperio** [comment]
Hi @fromanirh. Sadly I think you are going to have a very difficult time reproducing this bug. As stated before the VM that produced the panic had some serious issues and has already been pulled offline. 

My assumption was that there was just a missing check before reading `/numa_node` but this may be an edge case so rare it is not worth fixing.
