### ISSUE TITLE
Could not collect windows disk partition infomation

### ISSUE THREAD

**Issue by Zzorz** [jaypipes/ghw#267]
There is a bug in ghw/pkg/block/block_windows.go 
`https://github.com/jaypipes/ghw/blob/f38192d6ca0e6d937e83bda5fd17f4870b4db014/pkg/block/block_windows.go#L118`
The comparison between `* uint32` and `* uint32` would be wrong in this circumstance.

Bug can be fixed with method below:
```
...
if *diskdrive.Index == *diskpartition.DiskIndex {
    ...
}
```

**Comment by zackbloom** [comment]
Any chance this fix could get merged? Thank you for looking!

**Comment by jaypipes** [comment]
Fix is in https://github.com/jaypipes/ghw/releases/tag/v0.10.0

**Comment by zackbloom** [comment]
Thank you so much!
