### ISSUE TITLE
update golang stack in CI

### ISSUE THREAD

**Issue by fromanirh** [jaypipes/ghw#289]
Currently we support golang 1.14, 1.15 and 1.16 on CI. Golang 1.17 was released quite some time ago and got already patch releases, and golang 1.18 is not too far ahead.
Let's rotate our supported versions and run golang 1.15, 1.16 and 1.17 on CI.
I expect new lint/fmt fixes coming with this update.

**Comment by jaypipes** [comment]
Agreed, @fromanirh. I've been developing with 1.17 on my local workstation for a while now. Our [go.mod is currently at `1.12`](https://github.com/jaypipes/ghw/blob/004673db31bce4f54fa4f5525a9712d03710e999/go.mod#L3). Shall we up that to 1.15?

**Comment by fromanirh** [comment]
> Agreed, @fromanirh. I've been developing with 1.17 on my local workstation for a while now. Our [go.mod is currently at `1.12`](https://github.com/jaypipes/ghw/blob/004673db31bce4f54fa4f5525a9712d03710e999/go.mod#L3). Shall we up that to 1.15?

Yes. I'do as part of this PR
