### ISSUE TITLE
HDD is classified as SSD on windows 10

### ISSUE THREAD

**Issue by williambrode** [jaypipes/ghw#339]
I was trying out the lib on windows 10 and was surprised to see that it was misclassifying my HDD as an SSD.  Turns out the currently logic just says all "fixed" media types are SSD, which is incorrect.  The "fixed" media type simply means the disk is internal to the PC, so its not "removable" media for example like a USB drive.  I have what I believe to be the correct code (working for me locally) that I will create a PR for.

**Comment by jaypipes** [comment]
Awesome, thanks @williambrode!
