### ISSUE TITLE
Linux:  failed to determine memory area for node: open /sys/devices/system/node/node0/memory_failure/state: no such file or directory

### ISSUE THREAD

**Issue by matildeY** [jaypipes/ghw#341]
Failed to get topologyNodes return error
`failed to determine memory area for node: open /sys/devices/system/node/node0/memory_failure/state: no such file or directory`
 
 1- since latest linux kernel there is a new directory called "memory_failure" that matches pattern defined in function `memoryTotalPhysicalBytesFromPath`  and makes it failed.
 
 2- is it possible to call "memTotalPhysicalBytes" instead of "memoryTotalPhysicalBytesFromPath" in function "AreaForNode"  which contains a fallback function to the syslog approach ?

**Comment by jaypipes** [comment]
> hi, thanks for your answer, before submitting this bug i've tried with the main branch and the error is still present.
> 
> The memoryTotalUsableBytesFromPath call is ok and does not return error

OK, thank you for verifying that @matildeY! I will push a fix ASAP.

**Comment by asiffer** [comment]
Hi! I got the same warning when calling `ghw.GPU` :
`WARNING: failed to determine memory area for node: open /sys/devices/system/node/node0/memory_failure/state: no such file or directory`
(it is hidden when I use the `ghw.WithDisableWarnings()` option)

**Comment by jaypipes** [comment]
> Hi! I got the same warning when calling `ghw.GPU` : `WARNING: failed to determine memory area for node: open /sys/devices/system/node/node0/memory_failure/state: no such file or directory` (it is hidden when I use the `ghw.WithDisableWarnings()` option)

Hi @asiffer! What version of `ghw` are you using? I believe I fixed that issue but have not yet cut a new release of `ghw` that includes it.

**Comment by asiffer** [comment]
`v0.10.0` in my `go.mod` file

**Comment by jaypipes** [comment]
@asiffer I just cut a new release: https://github.com/jaypipes/ghw/releases/tag/v0.11.0

Wait a bit for Go mod/packaging to publish the new package and then update your go.mod. Should be good to go after that! :)

**Comment by asiffer** [comment]
Awesome 🤩  Thanks a lot!

**Comment by ffromani** [comment]
@asiffer @matildeY 
Hi! could you please kindly confirm version v0.11.0 fixes your issues, so we can close this bug? Thanks!

**Comment by asiffer** [comment]
Yes the last version fixed it 👍🏻 Thanks again

**Comment by matildeY** [comment]
yes, it's ok for me. Thanks

**Comment by CapCreeperGR** [comment]
Doesn't seem to be fixed. I am getting this warning with 0.12.0

**Comment by ffromani** [comment]
> Doesn't seem to be fixed. I am getting this warning with 0.12.0

Hi, could you please give more details? e.g. which kernel version are you running?
