### ISSUE TITLE
Add HugePages info to AreaForNode

### ISSUE THREAD

**Issue by Traumeel** [jaypipes/ghw#371]
I am using Topology functionality to get info about cpu and mem in NUMA architecture. What I am currently missing is data about HugePages. At least HugePages_Total, HugePages_Free and currently set size.

Maybe you are willing to extend logic here

https://github.com/jaypipes/ghw/blob/main/pkg/memory/memory_linux.go#L63

and add info about HugePages.

In case I am missing something and this info can be obtained by some other means in the lib, please feel free to redirect me.

Cheers!

**Comment by jaypipes** [comment]
@ffromani @Traumeel apologies for not responding earlier! I must have missed this in my inbox :(

Yes, this seems like a straightforward enhancement. @Traumeel would you like to submit this feature or would you like one of us to handle it?

**Comment by ffromani** [comment]
No probs @jaypipes I noticed late as well :) 
Just in case, I'd be happy to help as backup.

**Comment by Traumeel** [comment]
> @ffromani @Traumeel apologies for not responding earlier! I must have missed this in my inbox :(

@jaypipes No worries, all good)

> Yes, this seems like a straightforward enhancement. @Traumeel would you like to submit this feature or would you like one of us to handle it?

I did PR, please have a look.

**Comment by jaypipes** [comment]
Closing this one out. The next release of ghw will include your feature, @Traumeel, thank you! :)
