### ISSUE TITLE
ghw needs a mascot/logo

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/ghw#38]
OK, it's not like we *need* a logo or mascot. :)

But it would be awesome if ghw got a cool little mascot or logo.

Comments and suggestions more than welcome! If I made one, it would end up looking like a lame stick-figure...

**Comment by retr0h** [comment]
> If I made one, it would end up looking like a lame stick-figure...

Same here...

Totally dorky but I'm no artist :) 

<img width="388" alt="screen shot 2018-09-03 at 10 28 08 pm" src="https://user-images.githubusercontent.com/9895/45011691-ae74a480-afc8-11e8-958b-a9d0d309af92.png">

**Comment by jaypipes** [comment]
LOL, well it's definitely better than I could do, @retr0h! That said, the "W" kind of looks oddly phallic to me...

**Comment by thetravischannel** [comment]
I made another one real quick.

![Asset 2](https://user-images.githubusercontent.com/17730193/73864128-bca2a200-4806-11ea-8dc4-7280a02958a0.png)

**Comment by jaypipes** [comment]
That is awesomesauce, Travis! :)

**Comment by jaypipes** [comment]
You want to push up a PR that adds that logo to the README?

**Comment by thetravischannel** [comment]
Sure thing, PR pushed.

**Comment by jaypipes** [comment]
You rock @thetravischannel! :) Thank you so much!
