### ISSUE TITLE
Unable to use ghw on MacOS

### ISSUE THREAD

**Issue by jaypipes** [jaypipes/ghw#39]
Everything written for ghw so far is Linux-centric (since that's what I work with).

It would be great to have ghw work on MacOS/Darwin. I think I can do that with minimal changes, since OSX is basically a Linux/BSD-like system

**Comment by ykcab** [comment]
referencing to the last response #8, I will do a pull request once I am certain what I have works for macOS.

**Comment by jpo-joyent** [comment]
Disks done (w/ plist dep) in https://github.com/jaypipes/ghw/pull/97 / https://github.com/jaypipes/ghw/pull/98.

**Comment by jpo-joyent** [comment]
Not sure how stable it actually is. Let's hope you're right :)

There's never been a single release, so I pinned the arbitrary latest commit in Gopkg.toml

**Comment by jaypipes** [comment]
Closing this out. We can have individual issues for support on MacOSX for each specific submodules in ghw (network, cpu, etc...)
