### ISSUE TITLE
Correctly parse the mountpoint in /etc/mtab

### ISSUE THREAD

**Issue by thehowl** [jaypipes/ghw#45]
Mountpoint with spaces, tabs, newlines exist. The solution to that is octal encoding:

>Therefore these characters are encoded in the files and the getmntent function takes care of the decoding while reading the entries back in. '\040' is used to encode a space character, '\011' to encode a tab character, '\012' to encode a newline character, and '\\\\' to encode a backslash.

From: https://www.gnu.org/software/libc/manual/html_node/mtab.html

I think it's generally safe to assume that `mtab`, being generated and not hand-written, will usually only contain these exceptions, although it's probably best to check if `getmntent` in libc parses the mountpoint generically (ie. by converting the octal to a byte and then using it as the proper byte) or it handles these cases only.

**Comment by jaypipes** [comment]
Cool, thanks for letting me know, @thehowl :) I'll see what I can do to put some tests together and correct. Thanks, again!

**Comment by jaypipes** [comment]
@thehowl Hi! Please let me know if PR #50 addresses this issue. Thanks!
