### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by charles-dawes** [jaypipes/ghw#48]
When trying to run "go get  github.com/jaypipes/ghw" I get the following output: 

PS C:\Users\cdawes\go\src\GoMonitoring> go get  github.com/jaypipes/ghw
github.com/jaypipes/pcidb
..\src\github.com\jaypipes\pcidb\pci.go:62:11: db.load undefined (type *PCIDB has no field or method load)

**Comment by jaypipes** [comment]
@charles-dawes for ghw, the Windows support issue is Issue #8.

I've created a similar issue in pcidb library here: https://github.com/jaypipes/pcidb/issues/1

I'm going to close this issue out since it's a duplicate of Issue #8
