### ISSUE TITLE
Correct lint errors

### ISSUE THREAD

**Issue by retr0h** [jaypipes/ghw#51]
We have a lint target in the Makefile that fails in wonderful ways.  We should fix those lint errors or remove the target.  Ultimately, it would be nice to add to the `test` target.

**Comment by jackwilsdon** [comment]
Some of these fixes are breaking changes, such as `Id` → `ID` — what should be done about those?

**Comment by jaypipes** [comment]
@jackwilsdon Hi! Great question :)

I think probably the best thing to do would be to *add* a new ID field to the appropriate places, keep the old Id fields in place, but mark them as deprecated in 0.1 and will be removed entirely in 0.3 release.

Thoughts?

**Comment by fromanirh** [comment]
to close this issue, do we want to add a CI lane which calls golint-ci against the PRs?

**Comment by jaypipes** [comment]
> to close this issue, do we want to add a CI lane which calls golint-ci against the PRs?

sure, if you would like to do that, I'm all for it, Francesco!

**Comment by fromanirh** [comment]
> > to close this issue, do we want to add a CI lane which calls golint-ci against the PRs?
> 
> sure, if you would like to do that, I'm all for it, Francesco!

So let's do it! PR: https://github.com/jaypipes/ghw/pull/288 (currently WIP, not worth reviewing yet)

**Comment by fromanirh** [comment]
https://github.com/jaypipes/ghw/pull/288 is now reviewable
