### ISSUE TITLE
Support alternate root mountpoints

### ISSUE THREAD

**Issue by chiptus** [jaypipes/ghw#56]
Hi, 

First, thanks for this robust solution, I'm hoping to use it,
I have a specific use case where I want to run this library inside a docker container to get info about the host, and in that case, if understand correctly how your library works, the paths should be changed to where I bind the host folders to (e.g /host/proc). Do you think it's a doable change - to make the default paths changeable?

Thanks

**Comment by chiptus** [comment]
it seems like the container share a lot of info with the host and thus `pci.listdevices` and on the container give almost the same info as the host.

**Comment by jaypipes** [comment]
Hi @chiptus! Thanks for trying out ghw :) I'm a little uncertain what you mean by changing the default folders. Maybe you could elaborate on your request?

The Travis CI system which tests each commit to ghw actually runs in a container, so I'm pretty sure that whether or not the ghw is installed in a container, a virtual machine, or on baremetal should not matter. Certainly, if it does matter, then I want to fix things up!

Can you give me some details regarding what *type* of container you are using? Is it a privileged (system) container with a full root filesystem? Is it a simple application container with only a couple mountpoints (for /etc and container-local applications mountpoints)?

Is there a specific error you are seeing when you run ghw? If so, please paste it here and I'll see what I can do about making ghw more tolerant to the kinds of application containers you're using.

Thanks!
-jay

**Comment by deviantony** [comment]
Hi @jaypipes 

I'm working with @chiptus on this. Our goal would be to use the `ghw` library in a binary running inside a container to retrieve information about the host where the container is running.

Our assumption was that `ghw` reads its information from specific files on the filesystem (such as `/proc/cpuinfo` for CPU information). 

Thus, our idea was to bind-mount the `/` filesystem of the host into `/host` in the container (`docker run -v /:/host:ro mycontainer ...`) and to be able to customize the "base path" where `ghw` would retrieve its information (`/host` in this case, to be able to query `/host/proc/cpuinfo` for example).

We're not using any privileged container, it's basically a golang binary running inside a `scratch` image, root access should not be a problem.

**Comment by jaypipes** [comment]
Ah, @deviantony gotcha. Alrighty, lemme push something up later today that you can pull and test with, eh?

**Comment by deviantony** [comment]
@jaypipes sounds good ! Will be waiting for the update :-)

**Comment by jaypipes** [comment]
OK @chiptus and @deviantony, please give https://github.com/jaypipes/ghw/pull/58 a spin. That patch will enable you to set GHW_CHROOT to the host bind-mount path and should give you what you need. Lemme know what you think.

**Comment by deviantony** [comment]
@jaypipes thanks ! We'll test it ASAP

**Comment by jaypipes** [comment]
Closing this issue out. Let me know if you find any further issues using ghw in containers! Thanks! :)
