### ISSUE TITLE
numa_node for GPUs treated as a list... is it actually one?

### ISSUE THREAD

**Issue by jpo-joyent** [jaypipes/ghw#65]
At least for normal PCI devices, numa_node is just a single int.

See here: https://github.com/torvalds/linux/blob/v4.18/drivers/pci/pci-sysfs.c#L315-L350

Are GPUs somehow special due to SLI or CrossFire or whatever in that they can actually appear local to multiple numa nodes? Can you confirm this in code someplace?

If not, `gpuFillNUMANodes()`'s parsing could be simplified, and maybe GraphicsCard should have a single value for the topology node rather than a slice.

**Comment by jpo-joyent** [comment]
Also, should maybe be an int instead of a uint32, since -1 seems to be a valid value exposed by the kernel.

**Comment by jaypipes** [comment]
FYI, @jpo-joyent I'm not ignoring you on this one... it's just that $work has gotten in the way :)

**Comment by jaypipes** [comment]
And yes, I agree fully with the int vs uint32 idea. You can feel free to push a patch which changes all such identifiers to straight ints instead of uint32s.
