### ISSUE TITLE
get hash that calculated from all hardware identity

### ISSUE THREAD

**Issue by codenoid** [jaypipes/ghw#70]
example : 

ram 1 serial id + processor id + ghw.Disk.SerialNumber = md5 hash

**Comment by jaypipes** [comment]
By "identity" you are referring to the combination of all the hardware's functionality, resources (inventory) and other things?

What would this hash/identity be useful for? Just for determining if the hardware profile had changed?

**Comment by jaypipes** [comment]
Hi again @codenoid. I gave this feature request more thought this weekend and I've decided that this isn't something I want to include in `ghw` itself. You could, however, implement this in your application code yourself, basically looking at the different outputs of `ghw` and creating a hash identifier for the components of the system that you want to ensure are similar between hosts.

I'm going to close this issue out. Thanks!
-jay
