### ISSUE TITLE
Unable to use ghw on Windows

### ISSUE THREAD

**Issue by JamesCullum** [jaypipes/ghw#8]
The package sounds good, but I am unable to use it (Win10 x64). There are no instructions, so I simply ran `go get github.com/jaypipes/ghw`, which leads (during install & execution) to 

> go\src\github.com\jaypipes\ghw\block.go:36: undefined: blockFillInfo
> go\src\github.com\jaypipes\ghw\cpu.go:71: undefined: cpuFillInfo
> go\src\github.com\jaypipes\ghw\memory.go:17: undefined: memFillInfo
> go\src\github.com\jaypipes\ghw\net.go:47: undefined: netFillInfo
> go\src\github.com\jaypipes\ghw\topology.go:70: undefined: topologyFillInfo

**Comment by jaypipes** [comment]
Hi! Thanks for filing an issue, James :) I have only written the Linux-specific code so far.

I don't currently have a Win10 x64 box to test on (currently out of office with only a Linux laptop...) and therefore won't be able to write the code needed for Windows support for at least a couple weeks. Apologies!

Upon my return, I will try to complete Windows support for ghw.

**Comment by JamesCullum** [comment]
Thanks for the quick reply! Best of luck for the patches 👍

**Comment by ykcab** [comment]
@jaypipes I wanted to use your library, but this issue persists still (on macOS 10.13.6 17G65)
Are these function meant for windows?
```
blockFillInfo
cpuFillInfo
memFillInfo
netFillInfo
topologyFillInfo
```
As of my understanding so for we are missing these functions. I could not see them function defined anywhere in the entire library unless we do not have the latest version.
I also tried to removed them but I get a different result. I see that you named, for example, cpu, cpu_linux, gpu, gpu_linux, etc; i commented out the non _linux suffix to see if that what causing the error but I got undefined error these are the Struct elements declared in **HostInfo**:
```
../../jaypipes/ghw/main.go:10:12: undefined: MemoryInfo
../../jaypipes/ghw/main.go:11:12: undefined: BlockInfo
../../jaypipes/ghw/main.go:12:12: undefined: CPUInfo
../../jaypipes/ghw/main.go:13:12: undefined: TopologyInfo
../../jaypipes/ghw/main.go:14:12: undefined: NetworkInfo
../../jaypipes/ghw/main.go:15:12: undefined: GPUInfo
```

**Comment by retr0h** [comment]
Feels like we want to create an interface so unsupported OSes receive an error to implement vs undefined.

**Comment by jaypipes** [comment]
I don't have any Windows machines at the moment. I do however have a Macbook (that I hate using but fuck it, it's there so might as well test on it).

I'll see what I can do about getting something working for Mac today.

**Comment by jaypipes** [comment]
@ykcab it's mostly that I've got the following in all of the XXX_linux.go files:

```go
// +build linux
```

that needs to change to:

```go
// +build linux darwin
```

and I'm going to need to rename a few files it seems, from *_linux.go to something else, since it looks like go's build process ignores the `// +build` header line if the source file is named with a _linux.go suffix (it just assumes the file is only for Linux builds).

**Comment by jaypipes** [comment]
And of course, there's different ways of getting all the CPU, memory, block device information on Darwin than Linux, so I'll probably need to write custom *_darwin.go files it looks like :(

**Comment by ykcab** [comment]
If when we do "go run main.go" we could first check the OS platform before
building, in this case it will not throw fail the entire program.

**Comment by thehowl** [comment]
Isn't this pretty much the same as #9?

In any case, I'm gonna take a stab at this, I'll try getting most of the current API to be working on windows as well.

**Comment by jaypipes** [comment]
That's awesome, thank you @thehowl :) I still don't have any Windows images or VMs so I haven't been able to test anything on Windows.

**Comment by jaypipes** [comment]
And yes, I'll close out #9 since it's duplicative of this

**Comment by FairyTale5571** [comment]
No&
