### ISSUE TITLE
Update PciDB to next version

### ISSUE THREAD

**Issue by chiptus** [jaypipes/ghw#87]
my fix to pcidb added the ability to change chroot, together with fixing a bug that paths were ignored.
I want to make a PR but I guess the next version of pcidb should be released first.

**Comment by jaypipes** [comment]
Yup, I want to merge (in pcidb) the new Options-based New() PR along with a change to remove the "PCI" prefix from the structs in pcidb. I will then be cutting the 0.3 release of pcidb (hopefully today). After that, I'll start on the work to use pcidb 0.3 in ghw.

**Comment by chiptus** [comment]
great, thanks!

**Comment by chiptus** [comment]
totally works! thanks @jaypipes

**Comment by jaypipes** [comment]
rock on :)
